# Generated by Django 5.1.1 on 2024-09-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_vehicle_mileage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='mileage',
            new_name='estimated_mileage',
        ),
    ]
